language: node_js
node_js:
  - "4.1"
  - "0.10"
  - "0.12"
  - "4.4"
  - "5.10"
before_install:
  - "make check"
after_success:
  - '[ "${TRAVIS_NODE_VERSION}" = "4.4" ] && make codecovio'
dist: precise
